### PR TITLE
Update FormBuilder.php

### PR DESCRIPTION
**Pull request by tszyuloveyou**

### CODE REVIEW

**Comment by bfadamm** [comment]
@tszyuloveyou Why do we need this? Can't you use the method attribute?

**Comment by tszyuloveyou** [comment]
@bfadamm 
create,blade.php
```
{!! Form::open( [ "id" => "form", "method"=> "POST", "route" => "xxx.store" ] ) !!}
     @include('form')
{!! Form::close() !!}
<script src="from.js"></script >
```
edit,blade.php
```
{!! Form::model( $xxx, [ "id" => "form", "method"=> "PUT", "route" => "xxx.update" ] ) !!}
     @include('form')
{!! Form::close() !!}
<script src="from.js"></script >
```
from.js
```
.......
form.addEventListener(
    'submit', function(e) {
        // just display submit not actual send
        e.preventDefault();
        .......
        formData = new FormData();
        if( method != "GET" && method != "POST" ) {
            formData.append( "_method", method );
        }
        .......
```
because html is not support PUT, PATCH, DELECT.......
so, on the laravelcollective/html, it will use `method="POST"`
and add hidden input type `name="_method" value="{not support method}"`
so, if use `form.action` on create and edit page also return "POST"
but edit page should be "PUT"
when I use js to send ajax
if don't set dataset that for the method may I know what I should const or var.
or I should earh page add `data-method => {method }`
you don't think earh page add `data-method => {method }` too stupid?
I added `"method"=> "PUT"` than I also need to add `data-method => "PUT"`?
or I should create createForm.js and editForm.js,
edit one time I need to change two files?
my changing can let us just `const method = form.dataset.method;`

**Comment by themuddfamily** [comment]
> @bfadamm 
> create,blade.php
> ```
> {!! Form::open( [ "id" => "form", "method"=> "POST", "route" => "xxx.store" ] ) !!}
>      @include('form')
> {!! Form::close() !!}
> <script src="from.js"></script >
> ```
> edit,blade.php
> ```
> {!! Form::model( $xxx, [ "id" => "form", "method"=> "PUT", "route" => "xxx.update" ] ) !!}
>      @include('form')
> {!! Form::close() !!}
> <script src="from.js"></script >
> ```
> from.js
> ```
> .......
> form.addEventListener(
>     'submit', function(e) {
>         // just display submit not actual send
>         e.preventDefault();
>         .......
>         formData = new FormData();
>         if( method != "GET" && method != "POST" ) {
>             formData.append( "_method", method );
>         }
>         .......
> ```
> because html is not support PUT, PATCH, DELECT.......
> so, on the laravelcollective/html, it will use `method="POST"`
> and add hidden input type `name="_method" value="{not support method}"`
> so, if use `form.action` on create and edit page also return "POST"
> but edit page should be "PUT"
> when I use js to send ajax
> if don't set dataset that for the method may I know what I should const or var.
> or I should earh page add `data-method => {method }`
> you don't think earh page add `data-method => {method }` too stupid?
> I added `"method"=> "PUT"` than I also need to add `data-method => "PUT"`?
> or I should create createForm.js and editForm.js,
> edit one time I need to change two files?
> my changing can let us just `const method = form.dataset.method;`

I do have plans to fix this in a different way (it shouldn't be a JavaScript solution it should be laravel). But also you could just use form.getAttribute('method') until I release that? Then this change isn't required

**Comment by tszyuloveyou** [comment]
> > @bfadamm 
> > create,blade.php
> > ```
> > {!! Form::open( [ "id" => "form", "method"=> "POST", "route" => "xxx.store" ] ) !!}
> >      @include('form')
> > {!! Form::close() !!}
> > <script src="from.js"></script >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > edit,blade.php
> > ```
> > {!! Form::model( $xxx, [ "id" => "form", "method"=> "PUT", "route" => "xxx.update" ] ) !!}
> >      @include('form')
> > {!! Form::close() !!}
> > <script src="from.js"></script >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > from.js
> > ```
> > .......
> > form.addEventListener(
> >     'submit', function(e) {
> >         // just display submit not actual send
> >         e.preventDefault();
> >         .......
> >         formData = new FormData();
> >         if( method != "GET" && method != "POST" ) {
> >             formData.append( "_method", method );
> >         }
> >         .......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > because html is not support PUT, PATCH, DELECT.......
> > so, on the laravelcollective/html, it will use `method="POST"`
> > and add hidden input type `name="_method" value="{not support method}"`
> > so, if use `form.action` on create and edit page also return "POST"
> > but edit page should be "PUT"
> > when I use js to send ajax
> > if don't set dataset that for the method may I know what I should const or var.
> > or I should earh page add `data-method => {method }`
> > you don't think earh page add `data-method => {method }` too stupid?
> > I added `"method"=> "PUT"` than I also need to add `data-method => "PUT"`?
> > or I should create createForm.js and editForm.js,
> > edit one time I need to change two files?
> > my changing can let us just `const method = form.dataset.method;`
> 
> I do have plans to fix this in a different way (it shouldn't be a JavaScript solution it should be laravel). But also you could just use form.getAttribute('method') until I release that? Then this change isn't required


@themuddfamily , I would like to know what your solution is.
because this issus is from HTML standard,
if you want to change the method type without GET and POST
eg: `<form method="PUT" ......>`
you need to change HTML standard that at least wait to html 5.1/6 release and if html 5.1/6 support form can use without get and post
you just change laravel that cannot fix it
https://html.spec.whatwg.org/multipage/forms.html#element-attrdef-form-method

**Pull request closed without merging**
