### PR TITLE
[WIP] HtmlString instead of string

### PR DESCRIPTION
**Pull request by mgralikowski**
It is WIP (more files need to be changed) because first, I want to know what is behind choosing string instead of the HtmlString instance.

In my case, this change crashed our whole system:
image

HtmlString is easier to use and has additional methods, so is much more flexible. 

Ps. By accident I committed two changes, this PR also fixes this issue:
image
Probably it is because I use macro functionality and a custom service provider and the token is not available yet.

### CODE REVIEW

**Comment by themuddfamily** [comment]
@mgralikowski Hey! Thank you for the pull request, you're getting this because you're using {{ Form::XYZ }} instead of {!! Form::XYZ !!}

I will update this so it supports HtmlString now. I cannot accept your pull request though as it drops all the features I have added in 7.x

**Comment by mgralikowski** [comment]
Of course, I know the difference between {{ and {!! but in the case of this library, it was never necessary. I personally avoid using {!! !!} as much as possible, and If I trust the data that I want to display, I use `HtmlString`. 

Still, I don't understand Your motivation. I am very curious about what functionality brings returning standard strings?

**Comment by themuddfamily** [comment]
> Of course, I know the difference between {{ and {!! but in the case of this library, it was never necessary. I personally avoid using {!! !!} as much as possible, and If I trust the data that I want to display, I use `HtmlString`. 
> 
> Still, I don't understand Your motivation. I am very curious about what functionality brings returning standard strings?

My goal in removing it was that there's no consistency in how it's used, many projects I have encountered using laravel collective have mixed usage of {{ }} and {!! !!} (Likely from developers using different documentation). I think making it very clear it's html using {!! !!} Is the right syntax but also I see your point in it breaking previous implementations. I guess this is why nothing has been done about it previously.

**Comment by themuddfamily** [comment]
> Of course, I know the difference between {{ and {!! but in the case of this library, it was never necessary. I personally avoid using {!! !!} as much as possible, and If I trust the data that I want to display, I use `HtmlString`.
> 
> Still, I don't understand Your motivation. I am very curious about what functionality brings returning standard strings?

But anyway this should now be fixed with the latest version of the package :)

**Comment by mgralikowski** [comment]
Old, origin library:
https://laravel.com/docs/4.2/html
Spatie's alternative:
https://spatie.be/docs/laravel-html/v3/general-usage/core-concepts
Use `{{ }}` syntax.

The only place where I found one usage of `{!! !!}` is the first snippet here:
https://laravelcollective.com/docs/6.x/html#opening-a-form but all others use `echo` and `{{ }}`.

I and my colleagues almost never used  `{!! !!}`. Note that these exclamation marks are there specifically to point out that we are displaying something potentially dangerous in this particular place. I consider my forms safe :) We use `{!! !!}` to display some dynamic content, for example from WYSIWYG, so very rarely (<1%).

**Comment by mgralikowski** [comment]
PS. You have included/mixed those 2 alternative syntax in your documentation as well ;)

**Comment by bfadamm** [comment]
> Old, origin library: https://laravel.com/docs/4.2/html Spatie's alternative: https://spatie.be/docs/laravel-html/v3/general-usage/core-concepts Use `{{ }}` syntax.
> 
> The only place where I found one usage of `{!! !!}` is the first snippet here: https://laravelcollective.com/docs/6.x/html#opening-a-form but all others use `echo` and `{{ }}`.
> 
> I and my colleagues almost never used `{!! !!}`. Note that these exclamation marks are there specifically to point out that we are displaying something potentially dangerous in this particular place. I consider my forms safe :) We use `{!! !!}` to display some dynamic content, for example from WYSIWYG, so very rarely (<1%).

(On my other account because I'm replying at work haha)

Don't get me wrong I now see why you're using that way now and I'll carry on using HtmlString. It is potentially dangerous as if you put Forms inside of forms or HTML inside of buttons it will not escape and the intended function is to output HTML.

I'm pretty sure {{ echo Form::X() }} would require the {!! !!} syntax to work although I haven't tested this, as echo would cause it to be converted to a string.


> PS. You have included/mixed those 2 alternative syntax in your documentation as well ;)

I did notice this when I was writing it but one of the features I want to add (soon) are form packs for common frameworks so this section will be rewritten completely. There were quite a few other places I had changed it :D


----

To be completely honest I didn't even know of HtmlStrings existence until I took this project on!!

**Comment by mgralikowski** [comment]
`{!! !!}` and  `{{ }}` + HtmlString interface generate 1:1 the same final HTML result so work 100% the same way and both options have an equal level of security. There aren't any Form issues, trust me, if they existed, I would know them for sure :)

image

If you take a look of usage HtmlStrings you noticed that it has been added specially for such a situation. A lot of libraries like breadcrumbs generator, admin panels, and form generator use them to prevent using {!! and any on-fly modifications.

**Pull request closed without merging**
